#!/bin/sh
set -e

echo "Running RuboCop..."
bin/rubocop -f github

echo "Building frontend..."
bin/vite build --mode development
rm -rf public/vite-dev

echo "Running frontend tests..."
npm test

echo "Running Rails tests..."
RAILS_ENV=test bin/rails db:test:prepare
RAILS_ENV=test bin/rails test
