require "active_support/core_ext/integer/time"
# Loaded directly, not autoloaded: this file runs before Zeitwerk can resolve
# an app/ constant, and `config.middleware.use` needs the actual class right
# away (a string here builds a middleware stack entry that can never
# instantiate — Rails does not revisit it to constantize later).
require_relative "../../app/middleware/redirect_localhost_to_loopback"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Same background-job stack as production, so the recurring Spotify sync
  # runs locally too (started by `bin/jobs`, which `bin/dev` boots for you).
  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Lets the Prometheus container in observability/docker-compose.yml scrape
  # /metrics — from inside Docker the app is reached as host.docker.internal
  # rather than 127.0.0.1/localhost, which Host Authorization otherwise
  # blocks with a 403 before AdminBasicAuth even runs.
  config.hosts << "host.docker.internal"

  # /listen/callback's redirect_uri mirrors whatever host served the page, so
  # visiting via "localhost" instead of "127.0.0.1" sends Spotify a
  # redirect_uri it doesn't recognize — see the require_relative above and
  # RedirectLocalhostToLoopback itself.
  config.middleware.use RedirectLocalhostToLoopback

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Flags N+1 queries and unused eager loading as they happen, rather than
  # relying on someone noticing an extra SELECT in the log.
  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = false
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
  end
end
